name: My Instagram Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - run: sudo npm install -g typescript @angular/cli
      - run: npm install --save-dev
      - run: npm audit --omit=dev || true
      - run: ng lint
      - run: ng build --configuration production
      - run: (cd dist; zip -rp9 ../extension.zip *)
      - uses: actions/upload-artifact@v3
        with:
          name: extension.zip
          path: extension.zip
