name: My Instagram Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4
      - run: sudo npm install -g typescript @angular/cli
      - run: npm install --save-dev
      - run: npm audit || true
      - run: ng lint
